require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AgencySubscriptionsController do

  # This should return the minimal set of attributes required to create a valid
  # AgencySubscription. As you add validations to AgencySubscription, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "email" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AgencySubscriptionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all agency_subscriptions as @agency_subscriptions" do
      agency_subscription = AgencySubscription.create! valid_attributes
      get :index, {}, valid_session
      assigns(:agency_subscriptions).should eq([agency_subscription])
    end
  end

  describe "GET show" do
    it "assigns the requested agency_subscription as @agency_subscription" do
      agency_subscription = AgencySubscription.create! valid_attributes
      get :show, {:id => agency_subscription.to_param}, valid_session
      assigns(:agency_subscription).should eq(agency_subscription)
    end
  end

  describe "GET new" do
    it "assigns a new agency_subscription as @agency_subscription" do
      get :new, {}, valid_session
      assigns(:agency_subscription).should be_a_new(AgencySubscription)
    end
  end

  describe "GET edit" do
    it "assigns the requested agency_subscription as @agency_subscription" do
      agency_subscription = AgencySubscription.create! valid_attributes
      get :edit, {:id => agency_subscription.to_param}, valid_session
      assigns(:agency_subscription).should eq(agency_subscription)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AgencySubscription" do
        expect {
          post :create, {:agency_subscription => valid_attributes}, valid_session
        }.to change(AgencySubscription, :count).by(1)
      end

      it "assigns a newly created agency_subscription as @agency_subscription" do
        post :create, {:agency_subscription => valid_attributes}, valid_session
        assigns(:agency_subscription).should be_a(AgencySubscription)
        assigns(:agency_subscription).should be_persisted
      end

      it "redirects to the created agency_subscription" do
        post :create, {:agency_subscription => valid_attributes}, valid_session
        response.should redirect_to(AgencySubscription.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved agency_subscription as @agency_subscription" do
        # Trigger the behavior that occurs when invalid params are submitted
        AgencySubscription.any_instance.stub(:save).and_return(false)
        post :create, {:agency_subscription => { "email" => "invalid value" }}, valid_session
        assigns(:agency_subscription).should be_a_new(AgencySubscription)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AgencySubscription.any_instance.stub(:save).and_return(false)
        post :create, {:agency_subscription => { "email" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested agency_subscription" do
        agency_subscription = AgencySubscription.create! valid_attributes
        # Assuming there are no other agency_subscriptions in the database, this
        # specifies that the AgencySubscription created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AgencySubscription.any_instance.should_receive(:update).with({ "email" => "MyString" })
        put :update, {:id => agency_subscription.to_param, :agency_subscription => { "email" => "MyString" }}, valid_session
      end

      it "assigns the requested agency_subscription as @agency_subscription" do
        agency_subscription = AgencySubscription.create! valid_attributes
        put :update, {:id => agency_subscription.to_param, :agency_subscription => valid_attributes}, valid_session
        assigns(:agency_subscription).should eq(agency_subscription)
      end

      it "redirects to the agency_subscription" do
        agency_subscription = AgencySubscription.create! valid_attributes
        put :update, {:id => agency_subscription.to_param, :agency_subscription => valid_attributes}, valid_session
        response.should redirect_to(agency_subscription)
      end
    end

    describe "with invalid params" do
      it "assigns the agency_subscription as @agency_subscription" do
        agency_subscription = AgencySubscription.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AgencySubscription.any_instance.stub(:save).and_return(false)
        put :update, {:id => agency_subscription.to_param, :agency_subscription => { "email" => "invalid value" }}, valid_session
        assigns(:agency_subscription).should eq(agency_subscription)
      end

      it "re-renders the 'edit' template" do
        agency_subscription = AgencySubscription.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AgencySubscription.any_instance.stub(:save).and_return(false)
        put :update, {:id => agency_subscription.to_param, :agency_subscription => { "email" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested agency_subscription" do
      agency_subscription = AgencySubscription.create! valid_attributes
      expect {
        delete :destroy, {:id => agency_subscription.to_param}, valid_session
      }.to change(AgencySubscription, :count).by(-1)
    end

    it "redirects to the agency_subscriptions list" do
      agency_subscription = AgencySubscription.create! valid_attributes
      delete :destroy, {:id => agency_subscription.to_param}, valid_session
      response.should redirect_to(agency_subscriptions_url)
    end
  end

end
