require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CitizenshipsController do

  # This should return the minimal set of attributes required to create a valid
  # Citizenship. As you add validations to Citizenship, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CitizenshipsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all citizenships as @citizenships" do
      citizenship = Citizenship.create! valid_attributes
      get :index, {}, valid_session
      assigns(:citizenships).should eq([citizenship])
    end
  end

  describe "GET show" do
    it "assigns the requested citizenship as @citizenship" do
      citizenship = Citizenship.create! valid_attributes
      get :show, {:id => citizenship.to_param}, valid_session
      assigns(:citizenship).should eq(citizenship)
    end
  end

  describe "GET new" do
    it "assigns a new citizenship as @citizenship" do
      get :new, {}, valid_session
      assigns(:citizenship).should be_a_new(Citizenship)
    end
  end

  describe "GET edit" do
    it "assigns the requested citizenship as @citizenship" do
      citizenship = Citizenship.create! valid_attributes
      get :edit, {:id => citizenship.to_param}, valid_session
      assigns(:citizenship).should eq(citizenship)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Citizenship" do
        expect {
          post :create, {:citizenship => valid_attributes}, valid_session
        }.to change(Citizenship, :count).by(1)
      end

      it "assigns a newly created citizenship as @citizenship" do
        post :create, {:citizenship => valid_attributes}, valid_session
        assigns(:citizenship).should be_a(Citizenship)
        assigns(:citizenship).should be_persisted
      end

      it "redirects to the created citizenship" do
        post :create, {:citizenship => valid_attributes}, valid_session
        response.should redirect_to(Citizenship.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved citizenship as @citizenship" do
        # Trigger the behavior that occurs when invalid params are submitted
        Citizenship.any_instance.stub(:save).and_return(false)
        post :create, {:citizenship => { "name" => "invalid value" }}, valid_session
        assigns(:citizenship).should be_a_new(Citizenship)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Citizenship.any_instance.stub(:save).and_return(false)
        post :create, {:citizenship => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested citizenship" do
        citizenship = Citizenship.create! valid_attributes
        # Assuming there are no other citizenships in the database, this
        # specifies that the Citizenship created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Citizenship.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => citizenship.to_param, :citizenship => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested citizenship as @citizenship" do
        citizenship = Citizenship.create! valid_attributes
        put :update, {:id => citizenship.to_param, :citizenship => valid_attributes}, valid_session
        assigns(:citizenship).should eq(citizenship)
      end

      it "redirects to the citizenship" do
        citizenship = Citizenship.create! valid_attributes
        put :update, {:id => citizenship.to_param, :citizenship => valid_attributes}, valid_session
        response.should redirect_to(citizenship)
      end
    end

    describe "with invalid params" do
      it "assigns the citizenship as @citizenship" do
        citizenship = Citizenship.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Citizenship.any_instance.stub(:save).and_return(false)
        put :update, {:id => citizenship.to_param, :citizenship => { "name" => "invalid value" }}, valid_session
        assigns(:citizenship).should eq(citizenship)
      end

      it "re-renders the 'edit' template" do
        citizenship = Citizenship.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Citizenship.any_instance.stub(:save).and_return(false)
        put :update, {:id => citizenship.to_param, :citizenship => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested citizenship" do
      citizenship = Citizenship.create! valid_attributes
      expect {
        delete :destroy, {:id => citizenship.to_param}, valid_session
      }.to change(Citizenship, :count).by(-1)
    end

    it "redirects to the citizenships list" do
      citizenship = Citizenship.create! valid_attributes
      delete :destroy, {:id => citizenship.to_param}, valid_session
      response.should redirect_to(citizenships_url)
    end
  end

end
