require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EyesController do

  # This should return the minimal set of attributes required to create a valid
  # Eye. As you add validations to Eye, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EyesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all eyes as @eyes" do
      eye = Eye.create! valid_attributes
      get :index, {}, valid_session
      assigns(:eyes).should eq([eye])
    end
  end

  describe "GET show" do
    it "assigns the requested eye as @eye" do
      eye = Eye.create! valid_attributes
      get :show, {:id => eye.to_param}, valid_session
      assigns(:eye).should eq(eye)
    end
  end

  describe "GET new" do
    it "assigns a new eye as @eye" do
      get :new, {}, valid_session
      assigns(:eye).should be_a_new(Eye)
    end
  end

  describe "GET edit" do
    it "assigns the requested eye as @eye" do
      eye = Eye.create! valid_attributes
      get :edit, {:id => eye.to_param}, valid_session
      assigns(:eye).should eq(eye)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Eye" do
        expect {
          post :create, {:eye => valid_attributes}, valid_session
        }.to change(Eye, :count).by(1)
      end

      it "assigns a newly created eye as @eye" do
        post :create, {:eye => valid_attributes}, valid_session
        assigns(:eye).should be_a(Eye)
        assigns(:eye).should be_persisted
      end

      it "redirects to the created eye" do
        post :create, {:eye => valid_attributes}, valid_session
        response.should redirect_to(Eye.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved eye as @eye" do
        # Trigger the behavior that occurs when invalid params are submitted
        Eye.any_instance.stub(:save).and_return(false)
        post :create, {:eye => { "name" => "invalid value" }}, valid_session
        assigns(:eye).should be_a_new(Eye)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Eye.any_instance.stub(:save).and_return(false)
        post :create, {:eye => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested eye" do
        eye = Eye.create! valid_attributes
        # Assuming there are no other eyes in the database, this
        # specifies that the Eye created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Eye.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => eye.to_param, :eye => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested eye as @eye" do
        eye = Eye.create! valid_attributes
        put :update, {:id => eye.to_param, :eye => valid_attributes}, valid_session
        assigns(:eye).should eq(eye)
      end

      it "redirects to the eye" do
        eye = Eye.create! valid_attributes
        put :update, {:id => eye.to_param, :eye => valid_attributes}, valid_session
        response.should redirect_to(eye)
      end
    end

    describe "with invalid params" do
      it "assigns the eye as @eye" do
        eye = Eye.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Eye.any_instance.stub(:save).and_return(false)
        put :update, {:id => eye.to_param, :eye => { "name" => "invalid value" }}, valid_session
        assigns(:eye).should eq(eye)
      end

      it "re-renders the 'edit' template" do
        eye = Eye.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Eye.any_instance.stub(:save).and_return(false)
        put :update, {:id => eye.to_param, :eye => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested eye" do
      eye = Eye.create! valid_attributes
      expect {
        delete :destroy, {:id => eye.to_param}, valid_session
      }.to change(Eye, :count).by(-1)
    end

    it "redirects to the eyes list" do
      eye = Eye.create! valid_attributes
      delete :destroy, {:id => eye.to_param}, valid_session
      response.should redirect_to(eyes_url)
    end
  end

end
