require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HairsController do

  # This should return the minimal set of attributes required to create a valid
  # Hair. As you add validations to Hair, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "color" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HairsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all hairs as @hairs" do
      hair = Hair.create! valid_attributes
      get :index, {}, valid_session
      assigns(:hairs).should eq([hair])
    end
  end

  describe "GET show" do
    it "assigns the requested hair as @hair" do
      hair = Hair.create! valid_attributes
      get :show, {:id => hair.to_param}, valid_session
      assigns(:hair).should eq(hair)
    end
  end

  describe "GET new" do
    it "assigns a new hair as @hair" do
      get :new, {}, valid_session
      assigns(:hair).should be_a_new(Hair)
    end
  end

  describe "GET edit" do
    it "assigns the requested hair as @hair" do
      hair = Hair.create! valid_attributes
      get :edit, {:id => hair.to_param}, valid_session
      assigns(:hair).should eq(hair)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Hair" do
        expect {
          post :create, {:hair => valid_attributes}, valid_session
        }.to change(Hair, :count).by(1)
      end

      it "assigns a newly created hair as @hair" do
        post :create, {:hair => valid_attributes}, valid_session
        assigns(:hair).should be_a(Hair)
        assigns(:hair).should be_persisted
      end

      it "redirects to the created hair" do
        post :create, {:hair => valid_attributes}, valid_session
        response.should redirect_to(Hair.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved hair as @hair" do
        # Trigger the behavior that occurs when invalid params are submitted
        Hair.any_instance.stub(:save).and_return(false)
        post :create, {:hair => { "color" => "invalid value" }}, valid_session
        assigns(:hair).should be_a_new(Hair)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Hair.any_instance.stub(:save).and_return(false)
        post :create, {:hair => { "color" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested hair" do
        hair = Hair.create! valid_attributes
        # Assuming there are no other hairs in the database, this
        # specifies that the Hair created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Hair.any_instance.should_receive(:update).with({ "color" => "MyString" })
        put :update, {:id => hair.to_param, :hair => { "color" => "MyString" }}, valid_session
      end

      it "assigns the requested hair as @hair" do
        hair = Hair.create! valid_attributes
        put :update, {:id => hair.to_param, :hair => valid_attributes}, valid_session
        assigns(:hair).should eq(hair)
      end

      it "redirects to the hair" do
        hair = Hair.create! valid_attributes
        put :update, {:id => hair.to_param, :hair => valid_attributes}, valid_session
        response.should redirect_to(hair)
      end
    end

    describe "with invalid params" do
      it "assigns the hair as @hair" do
        hair = Hair.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Hair.any_instance.stub(:save).and_return(false)
        put :update, {:id => hair.to_param, :hair => { "color" => "invalid value" }}, valid_session
        assigns(:hair).should eq(hair)
      end

      it "re-renders the 'edit' template" do
        hair = Hair.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Hair.any_instance.stub(:save).and_return(false)
        put :update, {:id => hair.to_param, :hair => { "color" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested hair" do
      hair = Hair.create! valid_attributes
      expect {
        delete :destroy, {:id => hair.to_param}, valid_session
      }.to change(Hair, :count).by(-1)
    end

    it "redirects to the hairs list" do
      hair = Hair.create! valid_attributes
      delete :destroy, {:id => hair.to_param}, valid_session
      response.should redirect_to(hairs_url)
    end
  end

end
