require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LangsController do

  # This should return the minimal set of attributes required to create a valid
  # Lang. As you add validations to Lang, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "language" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LangsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all langs as @langs" do
      lang = Lang.create! valid_attributes
      get :index, {}, valid_session
      assigns(:langs).should eq([lang])
    end
  end

  describe "GET show" do
    it "assigns the requested lang as @lang" do
      lang = Lang.create! valid_attributes
      get :show, {:id => lang.to_param}, valid_session
      assigns(:lang).should eq(lang)
    end
  end

  describe "GET new" do
    it "assigns a new lang as @lang" do
      get :new, {}, valid_session
      assigns(:lang).should be_a_new(Lang)
    end
  end

  describe "GET edit" do
    it "assigns the requested lang as @lang" do
      lang = Lang.create! valid_attributes
      get :edit, {:id => lang.to_param}, valid_session
      assigns(:lang).should eq(lang)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Lang" do
        expect {
          post :create, {:lang => valid_attributes}, valid_session
        }.to change(Lang, :count).by(1)
      end

      it "assigns a newly created lang as @lang" do
        post :create, {:lang => valid_attributes}, valid_session
        assigns(:lang).should be_a(Lang)
        assigns(:lang).should be_persisted
      end

      it "redirects to the created lang" do
        post :create, {:lang => valid_attributes}, valid_session
        response.should redirect_to(Lang.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lang as @lang" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lang.any_instance.stub(:save).and_return(false)
        post :create, {:lang => { "language" => "invalid value" }}, valid_session
        assigns(:lang).should be_a_new(Lang)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lang.any_instance.stub(:save).and_return(false)
        post :create, {:lang => { "language" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lang" do
        lang = Lang.create! valid_attributes
        # Assuming there are no other langs in the database, this
        # specifies that the Lang created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Lang.any_instance.should_receive(:update).with({ "language" => "" })
        put :update, {:id => lang.to_param, :lang => { "language" => "" }}, valid_session
      end

      it "assigns the requested lang as @lang" do
        lang = Lang.create! valid_attributes
        put :update, {:id => lang.to_param, :lang => valid_attributes}, valid_session
        assigns(:lang).should eq(lang)
      end

      it "redirects to the lang" do
        lang = Lang.create! valid_attributes
        put :update, {:id => lang.to_param, :lang => valid_attributes}, valid_session
        response.should redirect_to(lang)
      end
    end

    describe "with invalid params" do
      it "assigns the lang as @lang" do
        lang = Lang.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lang.any_instance.stub(:save).and_return(false)
        put :update, {:id => lang.to_param, :lang => { "language" => "invalid value" }}, valid_session
        assigns(:lang).should eq(lang)
      end

      it "re-renders the 'edit' template" do
        lang = Lang.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lang.any_instance.stub(:save).and_return(false)
        put :update, {:id => lang.to_param, :lang => { "language" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lang" do
      lang = Lang.create! valid_attributes
      expect {
        delete :destroy, {:id => lang.to_param}, valid_session
      }.to change(Lang, :count).by(-1)
    end

    it "redirects to the langs list" do
      lang = Lang.create! valid_attributes
      delete :destroy, {:id => lang.to_param}, valid_session
      response.should redirect_to(langs_url)
    end
  end

end
