require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OverallsizesController do

  # This should return the minimal set of attributes required to create a valid
  # Overallsize. As you add validations to Overallsize, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "overall_size" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OverallsizesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all overallsizes as @overallsizes" do
      overallsize = Overallsize.create! valid_attributes
      get :index, {}, valid_session
      assigns(:overallsizes).should eq([overallsize])
    end
  end

  describe "GET show" do
    it "assigns the requested overallsize as @overallsize" do
      overallsize = Overallsize.create! valid_attributes
      get :show, {:id => overallsize.to_param}, valid_session
      assigns(:overallsize).should eq(overallsize)
    end
  end

  describe "GET new" do
    it "assigns a new overallsize as @overallsize" do
      get :new, {}, valid_session
      assigns(:overallsize).should be_a_new(Overallsize)
    end
  end

  describe "GET edit" do
    it "assigns the requested overallsize as @overallsize" do
      overallsize = Overallsize.create! valid_attributes
      get :edit, {:id => overallsize.to_param}, valid_session
      assigns(:overallsize).should eq(overallsize)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Overallsize" do
        expect {
          post :create, {:overallsize => valid_attributes}, valid_session
        }.to change(Overallsize, :count).by(1)
      end

      it "assigns a newly created overallsize as @overallsize" do
        post :create, {:overallsize => valid_attributes}, valid_session
        assigns(:overallsize).should be_a(Overallsize)
        assigns(:overallsize).should be_persisted
      end

      it "redirects to the created overallsize" do
        post :create, {:overallsize => valid_attributes}, valid_session
        response.should redirect_to(Overallsize.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved overallsize as @overallsize" do
        # Trigger the behavior that occurs when invalid params are submitted
        Overallsize.any_instance.stub(:save).and_return(false)
        post :create, {:overallsize => { "overall_size" => "invalid value" }}, valid_session
        assigns(:overallsize).should be_a_new(Overallsize)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Overallsize.any_instance.stub(:save).and_return(false)
        post :create, {:overallsize => { "overall_size" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested overallsize" do
        overallsize = Overallsize.create! valid_attributes
        # Assuming there are no other overallsizes in the database, this
        # specifies that the Overallsize created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Overallsize.any_instance.should_receive(:update).with({ "overall_size" => "1" })
        put :update, {:id => overallsize.to_param, :overallsize => { "overall_size" => "1" }}, valid_session
      end

      it "assigns the requested overallsize as @overallsize" do
        overallsize = Overallsize.create! valid_attributes
        put :update, {:id => overallsize.to_param, :overallsize => valid_attributes}, valid_session
        assigns(:overallsize).should eq(overallsize)
      end

      it "redirects to the overallsize" do
        overallsize = Overallsize.create! valid_attributes
        put :update, {:id => overallsize.to_param, :overallsize => valid_attributes}, valid_session
        response.should redirect_to(overallsize)
      end
    end

    describe "with invalid params" do
      it "assigns the overallsize as @overallsize" do
        overallsize = Overallsize.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Overallsize.any_instance.stub(:save).and_return(false)
        put :update, {:id => overallsize.to_param, :overallsize => { "overall_size" => "invalid value" }}, valid_session
        assigns(:overallsize).should eq(overallsize)
      end

      it "re-renders the 'edit' template" do
        overallsize = Overallsize.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Overallsize.any_instance.stub(:save).and_return(false)
        put :update, {:id => overallsize.to_param, :overallsize => { "overall_size" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested overallsize" do
      overallsize = Overallsize.create! valid_attributes
      expect {
        delete :destroy, {:id => overallsize.to_param}, valid_session
      }.to change(Overallsize, :count).by(-1)
    end

    it "redirects to the overallsizes list" do
      overallsize = Overallsize.create! valid_attributes
      delete :destroy, {:id => overallsize.to_param}, valid_session
      response.should redirect_to(overallsizes_url)
    end
  end

end
